using MonoForge.Editor.Models;

namespace MonoForge.Editor.Services;

public static class LiveReload
{
    public const string ReloadTokenName = "_monoforge_reload.token";
    public const string LiveReloadSourceName = "MonoForgeLiveReload.cs";

    public static string ScenesDir(string projectRoot) => Path.Combine(projectRoot, "Content", "Scenes");

    public static void PushScene(string projectRoot, SceneDocument scene)
    {
        var dir = ScenesDir(projectRoot);
        Directory.CreateDirectory(dir);

        var safeName = (string.IsNullOrEmpty(scene.Name) ? "main" : scene.Name)
            .Replace(".collection", "", StringComparison.Ordinal)
            .Replace(Path.DirectorySeparatorChar, '_');
        var scenePath = Path.Combine(dir, safeName + ".scene.json");
        File.WriteAllText(scenePath, System.Text.Json.JsonSerializer.Serialize(scene, new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));

        var token = Path.Combine(dir, ReloadTokenName);
        File.WriteAllText(token, DateTime.UtcNow.ToString("o"));

        EnsureHelperClass(projectRoot);
    }

    /// <summary>
    /// Drops a copy-pasteable helper C# class into the project root the first time it runs.
    /// Devs `new MonoForgeLiveReload(Content)` and call .Update() in their game loop.
    /// </summary>
    private static void EnsureHelperClass(string projectRoot)
    {
        var path = Path.Combine(projectRoot, LiveReloadSourceName);
        if (File.Exists(path)) return;
        File.WriteAllText(path, HelperSource());
    }

    private static string HelperSource() => """
        // <auto-generated by MonoForge — safe to edit>
        using System;
        using System.IO;
        using Microsoft.Xna.Framework.Content;

        namespace MonoForge.Runtime;

        /// <summary>
        /// Watches Content/Scenes/_monoforge_reload.token and raises SceneChanged when the
        /// editor saves. Read the scene JSON from Content/Scenes/<name>.scene.json.
        /// </summary>
        public sealed class MonoForgeLiveReload
        {
            private readonly string _scenesDir;
            private DateTime _lastSeen = DateTime.MinValue;
            public event Action<string>? SceneChanged; // payload: scene JSON path

            public MonoForgeLiveReload(ContentManager content)
            {
                _scenesDir = Path.Combine(content.RootDirectory, "Scenes");
                if (Directory.Exists(_scenesDir))
                {
                    var token = Path.Combine(_scenesDir, "_monoforge_reload.token");
                    if (File.Exists(token)) _lastSeen = File.GetLastWriteTimeUtc(token);
                }
            }

            public void Update()
            {
                if (!Directory.Exists(_scenesDir)) return;
                var token = Path.Combine(_scenesDir, "_monoforge_reload.token");
                if (!File.Exists(token)) return;
                var ts = File.GetLastWriteTimeUtc(token);
                if (ts <= _lastSeen) return;
                _lastSeen = ts;

                foreach (var scene in Directory.EnumerateFiles(_scenesDir, "*.scene.json"))
                {
                    SceneChanged?.Invoke(scene);
                    return;
                }
            }
        }
        """;
}
