namespace MonoForge.Editor.Services;

/// <summary>
/// Emits a standalone .cs file that the user drops into their MonoGame (or any .NET)
/// project to load .mfmap documents at runtime. The generated file:
///   - Mirrors the MapDocument shape so System.Text.Json can deserialize verbatim.
///   - Exposes a static MapData.Load(path) entry point.
///   - Includes helpers (PositionVec, WorldMatrix, etc.) so consumers don't have to
///     rebuild trigonometry themselves.
/// The generated code intentionally has zero MonoForge / Avalonia dependencies.
/// </summary>
public static class MapRuntimeExporter
{
    public static string GenerateRuntimeCs(string targetNamespace = "MyGame.Maps")
    {
        return $$"""
// <auto-generated>
// Generated by MonoForge — do not edit by hand. Re-export from the editor
// (Map Editor → Export Runtime…) to refresh.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{targetNamespace}};

/// <summary>Top-level deserialized .mfmap document.</summary>
public sealed class MapData
{
    public string Name { get; set; } = "";
    public string Mode { get; set; } = "3D";
    public MapCameraData Camera { get; set; } = new();
    public List<MapEntityData> Entities { get; set; } = new();

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static MapData Load(string path)
    {
        var text = File.ReadAllText(path);
        return Deserialize(text);
    }

    public static MapData Deserialize(string json)
        => JsonSerializer.Deserialize<MapData>(json, Options) ?? new MapData();

    public IEnumerable<MapEntityData> EntitiesOfType(string type)
    {
        foreach (var e in Entities) if (e.Type == type) yield return e;
    }
}

/// <summary>Editor / runtime camera setup baked into the map.</summary>
public sealed class MapCameraData
{
    public float[] Position { get; set; } = { 0f, 6f, 12f };
    public float[] Target   { get; set; } = { 0f, 0f, 0f };
    public float FovDegrees { get; set; } = 60f;

    [JsonIgnore] public Vector3 PositionVec => new(Position[0], Position[1], Position[2]);
    [JsonIgnore] public Vector3 TargetVec   => new(Target[0],   Target[1],   Target[2]);
}

/// <summary>One placeable in a map. Inspect <c>Type</c> to know which fields are meaningful.</summary>
public sealed class MapEntityData
{
    public string Id    { get; set; } = "";
    public string Name  { get; set; } = "";
    /// <summary>"Empty" | "Model3D" | "Sprite" | "Light" | "Camera" | "Trigger" | "Text"</summary>
    public string Type  { get; set; } = "Empty";

    public float[] Position { get; set; } = { 0f, 0f, 0f };
    /// <summary>Euler XYZ in degrees.</summary>
    public float[] Rotation { get; set; } = { 0f, 0f, 0f };
    public float[] Scale    { get; set; } = { 1f, 1f, 1f };

    // Type-specific fields (only populated when relevant).
    public string? ModelPath   { get; set; }
    public string? TexturePath { get; set; }
    public string? Text        { get; set; }
    public string  Color       { get; set; } = "#ffffff";
    public string  TriggerShape   { get; set; } = "box";
    public float[] TriggerSize    { get; set; } = { 2f, 2f, 2f };
    public string  LightType      { get; set; } = "directional";
    public float   LightIntensity { get; set; } = 1f;

    [JsonIgnore] public Vector3 PositionVec => new(Position[0], Position[1], Position[2]);
    [JsonIgnore] public Vector3 RotationVec => new(Rotation[0], Rotation[1], Rotation[2]);
    [JsonIgnore] public Vector3 ScaleVec    => new(Scale[0],    Scale[1],    Scale[2]);

    /// <summary>TRS world matrix (Scale × Rotation × Translation, rotation order XYZ degrees).</summary>
    public Matrix4x4 WorldMatrix()
    {
        const float deg = MathF.PI / 180f;
        var r = Matrix4x4.CreateRotationX(Rotation[0] * deg)
              * Matrix4x4.CreateRotationY(Rotation[1] * deg)
              * Matrix4x4.CreateRotationZ(Rotation[2] * deg);
        var s = Matrix4x4.CreateScale(ScaleVec);
        var t = Matrix4x4.CreateTranslation(PositionVec);
        return s * r * t;
    }

    /// <summary>Parse #rrggbb hex (or #aarrggbb) to (a, r, g, b) bytes. Returns white on parse failure.</summary>
    public (byte A, byte R, byte G, byte B) ColorBytes()
    {
        var c = Color?.TrimStart('#') ?? "";
        if (c.Length == 6 && int.TryParse(c, System.Globalization.NumberStyles.HexNumber, null, out var rgb))
            return (255, (byte)((rgb >> 16) & 0xff), (byte)((rgb >> 8) & 0xff), (byte)(rgb & 0xff));
        if (c.Length == 8 && int.TryParse(c, System.Globalization.NumberStyles.HexNumber, null, out var argb))
            return ((byte)((argb >> 24) & 0xff), (byte)((argb >> 16) & 0xff), (byte)((argb >> 8) & 0xff), (byte)(argb & 0xff));
        return (255, 255, 255, 255);
    }
}

/*
EXAMPLE — Game1.cs:

    private MapData _map = null!;

    protected override void LoadContent()
    {
        _map = MapData.Load("Content/Levels/Level1.mfmap");
        foreach (var ent in _map.Entities)
        {
            switch (ent.Type)
            {
                case "Model3D":
                    // _models[ent.Id] = LoadGlb(ent.ModelPath!);
                    break;
                case "Light":
                    // RegisterLight(ent);
                    break;
                case "Camera":
                    if (ent.Name == "Main Camera")
                    {
                        // _camera.Position = ent.PositionVec;
                    }
                    break;
            }
        }
    }
*/

""";
    }
}
