using System.Globalization;
using System.Text;
using MonoForge.Editor.Models;

namespace MonoForge.Editor.Services;

public static class MonoGameSceneExporter
{
    public static string Export(SceneDocument scene)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated> by MonoForge");
        builder.AppendLine("using Microsoft.Xna.Framework;");
        builder.AppendLine("using Microsoft.Xna.Framework.Content;");
        builder.AppendLine("using Microsoft.Xna.Framework.Graphics;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace MonoForge.Generated;");
        builder.AppendLine();
        builder.AppendLine("public sealed class SceneSprite");
        builder.AppendLine("{");
        builder.AppendLine("    public string Id { get; init; } = \"\";");
        builder.AppendLine("    public string Name { get; init; } = \"\";");
        builder.AppendLine("    public string TextureName { get; init; } = \"\";");
        builder.AppendLine("    public Rectangle Bounds { get; set; }");
        builder.AppendLine("    public Color Tint { get; set; } = Color.White;");
        builder.AppendLine("    public int Layer { get; init; }");
        builder.AppendLine("    public bool Visible { get; set; } = true;");
        builder.AppendLine("    public Texture2D? Texture { get; set; }");
        builder.AppendLine("}");
        builder.AppendLine();

        var className = ToIdentifier(scene.Name.Replace(".collection", "", StringComparison.Ordinal));
        builder.AppendLine($"public sealed class {className}Scene");
        builder.AppendLine("{");
        builder.AppendLine("    public List<SceneSprite> Sprites { get; } = new();");
        builder.AppendLine("    private Texture2D? _pixel;");
        builder.AppendLine();
        builder.AppendLine($"    public {className}Scene()");
        builder.AppendLine("    {");

        foreach (var item in scene.Flatten())
        {
            var (r, g, b) = ParseHex(item.Color);
            var contentName = ToContentName(item.TexturePath);
            builder.AppendLine(CultureInfo.InvariantCulture,
                $"        Sprites.Add(new SceneSprite {{ Id = \"{Escape(item.Id)}\", Name = \"{Escape(item.Name)}\", TextureName = \"{contentName}\", Bounds = new Rectangle({Math.Round(item.X)}, {Math.Round(item.Y)}, {Math.Round(item.Width)}, {Math.Round(item.Height)}), Tint = new Color({r}, {g}, {b}), Layer = {item.Layer}, Visible = {item.Visible.ToString().ToLowerInvariant()} }});");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public void LoadContent(ContentManager content, GraphicsDevice graphics)");
        builder.AppendLine("    {");
        builder.AppendLine("        _pixel = new Texture2D(graphics, 1, 1);");
        builder.AppendLine("        _pixel.SetData(new[] { Color.White });");
        builder.AppendLine("        foreach (var sprite in Sprites)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!string.IsNullOrEmpty(sprite.TextureName))");
        builder.AppendLine("            {");
        builder.AppendLine("                try { sprite.Texture = content.Load<Texture2D>(sprite.TextureName); } catch { /* missing asset */ }");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public void Draw(SpriteBatch spriteBatch)");
        builder.AppendLine("    {");
        builder.AppendLine("        Sprites.Sort((a, b) => a.Layer.CompareTo(b.Layer));");
        builder.AppendLine("        foreach (var sprite in Sprites)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (!sprite.Visible) continue;");
        builder.AppendLine("            var tex = sprite.Texture ?? _pixel;");
        builder.AppendLine("            if (tex is null) continue;");
        builder.AppendLine("            spriteBatch.Draw(tex, sprite.Bounds, sprite.Tint);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToContentName(string texturePath)
    {
        if (string.IsNullOrEmpty(texturePath)) return "";
        return Path.GetFileNameWithoutExtension(texturePath);
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string ToIdentifier(string value)
    {
        var chars = value.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var safe = new string(chars);
        if (string.IsNullOrWhiteSpace(safe)) return "Object";
        return char.IsDigit(safe[0]) ? "_" + safe : safe;
    }

    private static (int R, int G, int B) ParseHex(string color)
    {
        var hex = color.TrimStart('#');
        if (hex.Length == 3) hex = string.Concat(hex.Select(c => $"{c}{c}"));
        if (hex.Length != 6 || !int.TryParse(hex[..2], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var r))
        {
            return (255, 255, 255);
        }
        var g = int.Parse(hex[2..4], NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        var b = int.Parse(hex[4..6], NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        return (r, g, b);
    }
}
