namespace MonoForge.Editor.Services;

public static class MonoGameModelExporter
{
    /// <summary>
    /// Emits a runtime helper class showing how to load + animate a GLB model in MonoGame
    /// using SharpGLTF for parsing and a simple LBS skinner. The user adds SharpGLTF as a
    /// PackageReference in their game project. The class works for static and skinned models.
    /// </summary>
    public static string Emit(string className = "ForgedModel")
    {
        return $$"""
            // <auto-generated> by MonoForge — copy this file into your MonoGame project.
            // Add: <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Numerics;
            using Microsoft.Xna.Framework;
            using Microsoft.Xna.Framework.Graphics;
            using SharpGLTF.Schema2;
            using XnaMatrix = Microsoft.Xna.Framework.Matrix;
            using XnaVector2 = Microsoft.Xna.Framework.Vector2;
            using XnaVector3 = Microsoft.Xna.Framework.Vector3;

            namespace MonoForge.Generated;

            /// <summary>
            /// Loads a glTF/GLB model, samples its animations on the CPU, applies linear
            /// blend skinning to vertices and renders with BasicEffect.
            /// </summary>
            public sealed class {{className}}
            {
                private readonly GraphicsDevice _gd;
                private readonly BasicEffect _effect;
                private readonly List<Primitive> _primitives = new();
                private readonly List<Joint> _joints = new();
                private readonly List<Clip> _clips = new();

                public XnaMatrix World = XnaMatrix.Identity;
                public XnaMatrix View;
                public XnaMatrix Projection;
                public int ActiveClip = -1;
                public float Time;
                public bool Loop = true;

                public IReadOnlyList<string> ClipNames => _clips.Select(c => c.Name).ToList();
                public float Duration => ActiveClip >= 0 && ActiveClip < _clips.Count ? _clips[ActiveClip].Duration : 0;

                public {{className}}(GraphicsDevice graphics, string path)
                {
                    _gd = graphics;
                    _effect = new BasicEffect(graphics)
                    {
                        VertexColorEnabled = false,
                        TextureEnabled = false,
                        LightingEnabled = true,
                        PreferPerPixelLighting = false
                    };
                    _effect.EnableDefaultLighting();
                    Load(path);
                }

                public void Update(float dt)
                {
                    if (ActiveClip < 0 || ActiveClip >= _clips.Count) return;
                    var d = _clips[ActiveClip].Duration;
                    if (d <= 0) return;
                    Time += dt;
                    if (Loop) Time = ((Time % d) + d) % d;
                    else if (Time > d) Time = d;
                }

                public void Draw()
                {
                    var pose = ComputeJointWorlds();
                    var skin = ComputeSkinMatrices(pose);

                    _effect.World = World;
                    _effect.View = View;
                    _effect.Projection = Projection;

                    foreach (var prim in _primitives)
                    {
                        var vbuf = prim.IsSkinned ? SkinVertices(prim, skin) : prim.BindVertices;
                        var vb = new VertexBuffer(_gd, VertexPositionNormalTexture.VertexDeclaration, vbuf.Length, BufferUsage.WriteOnly);
                        vb.SetData(vbuf);
                        var ib = new IndexBuffer(_gd, IndexElementSize.ThirtyTwoBits, prim.Indices.Length, BufferUsage.WriteOnly);
                        ib.SetData(prim.Indices);
                        _gd.SetVertexBuffer(vb);
                        _gd.Indices = ib;
                        foreach (var pass in _effect.CurrentTechnique.Passes)
                        {
                            pass.Apply();
                            _gd.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, prim.Indices.Length / 3);
                        }
                    }
                }

                // --- Loading -----------------------------------------------------------------

                private void Load(string path)
                {
                    var model = ModelRoot.Load(path);
                    var scene = model.DefaultScene ?? model.LogicalScenes[0];
                    var primarySkin = model.LogicalSkins.FirstOrDefault();
                    var jointMap = new Dictionary<Node, int>();
                    if (primarySkin is not null)
                    {
                        for (int j = 0; j < primarySkin.JointsCount; j++)
                        {
                            var (jn, ibm) = primarySkin.GetJoint(j);
                            jointMap[jn] = j;
                            var local = jn.LocalTransform;
                            _joints.Add(new Joint
                            {
                                Name = jn.Name ?? $"joint_{j}",
                                LocalT = local.Translation,
                                LocalR = local.Rotation,
                                LocalS = local.Scale,
                                InverseBind = ibm,
                                Parent = -1
                            });
                        }
                        for (int j = 0; j < primarySkin.JointsCount; j++)
                        {
                            var jn = primarySkin.GetJoint(j).Joint;
                            var p = jn.VisualParent;
                            _joints[j].Parent = p is not null && jointMap.TryGetValue(p, out var pi) ? pi : -1;
                        }
                    }

                    foreach (var node in scene.VisualChildren.SelectMany(Walk))
                    {
                        if (node.Mesh is null) continue;
                        var skinned = node.Skin is not null;
                        foreach (var p in node.Mesh.Primitives)
                        {
                            var posArr = p.GetVertexAccessor("POSITION")?.AsVector3Array();
                            if (posArr is null) continue;
                            var normArr = p.GetVertexAccessor("NORMAL")?.AsVector3Array();
                            var uvArr = p.GetVertexAccessor("TEXCOORD_0")?.AsVector2Array();
                            var jArr = p.GetVertexAccessor("JOINTS_0")?.AsVector4Array();
                            var wArr = p.GetVertexAccessor("WEIGHTS_0")?.AsVector4Array();
                            var idxArr = p.GetIndices();

                            var prim = new Primitive { IsSkinned = skinned && jArr is not null && wArr is not null };
                            prim.BindVertices = new VertexPositionNormalTexture[posArr.Count];
                            prim.Influences = prim.IsSkinned ? new Vector4[posArr.Count] : Array.Empty<Vector4>();
                            prim.Weights = prim.IsSkinned ? new Vector4[posArr.Count] : Array.Empty<Vector4>();
                            for (int i = 0; i < posArr.Count; i++)
                            {
                                var v = posArr[i];
                                var n = normArr is not null ? normArr[i] : Vector3.UnitY;
                                var uv = uvArr is not null ? uvArr[i] : Vector2.Zero;
                                if (!skinned)
                                {
                                    var m = node.WorldMatrix;
                                    v = Vector3.Transform(v, m);
                                    n = Vector3.Normalize(Vector3.TransformNormal(n, m));
                                }
                                prim.BindVertices[i] = new VertexPositionNormalTexture(
                                    new XnaVector3(v.X, v.Y, v.Z),
                                    new XnaVector3(n.X, n.Y, n.Z),
                                    new XnaVector2(uv.X, uv.Y));
                                if (prim.IsSkinned)
                                {
                                    prim.Influences[i] = jArr![i];
                                    prim.Weights[i] = wArr![i];
                                }
                            }
                            if (idxArr is not null)
                            {
                                prim.Indices = new int[idxArr.Count];
                                for (int i = 0; i < idxArr.Count; i++) prim.Indices[i] = (int)idxArr[i];
                            }
                            else
                            {
                                prim.Indices = Enumerable.Range(0, posArr.Count).ToArray();
                            }
                            _primitives.Add(prim);
                        }
                    }

                    foreach (var anim in model.LogicalAnimations)
                    {
                        var clip = new Clip { Name = anim.Name ?? $"anim_{anim.LogicalIndex}", Duration = anim.Duration };
                        foreach (var ch in anim.Channels)
                        {
                            if (!jointMap.TryGetValue(ch.TargetNode, out var ji)) continue;
                            var prop = ch.TargetNodePath.ToString().ToLowerInvariant();
                            var c = new Channel { JointIndex = ji, Property = prop };
                            try
                            {
                                if (prop == "translation")
                                {
                                    var kf = ch.GetTranslationSampler().GetLinearKeys().ToList();
                                    c.Times = kf.Select(k => k.Key).ToArray();
                                    c.Vec3 = kf.Select(k => k.Value).ToArray();
                                }
                                else if (prop == "rotation")
                                {
                                    var kf = ch.GetRotationSampler().GetLinearKeys().ToList();
                                    c.Times = kf.Select(k => k.Key).ToArray();
                                    c.Quat = kf.Select(k => k.Value).ToArray();
                                }
                                else if (prop == "scale")
                                {
                                    var kf = ch.GetScaleSampler().GetLinearKeys().ToList();
                                    c.Times = kf.Select(k => k.Key).ToArray();
                                    c.Vec3 = kf.Select(k => k.Value).ToArray();
                                }
                                else continue;
                            }
                            catch { continue; }
                            if (c.Times.Length > 0) clip.Channels.Add(c);
                        }
                        if (clip.Channels.Count > 0) _clips.Add(clip);
                    }
                    if (_clips.Count > 0) ActiveClip = 0;

                    static IEnumerable<Node> Walk(Node n)
                    {
                        yield return n;
                        foreach (var c in n.VisualChildren) foreach (var x in Walk(c)) yield return x;
                    }
                }

                // --- Animation + skinning ---------------------------------------------------

                private Matrix4x4[] ComputeJointWorlds()
                {
                    var locals = _joints.Select(j => (j.LocalT, j.LocalR, j.LocalS)).ToArray();
                    if (ActiveClip >= 0 && ActiveClip < _clips.Count)
                    {
                        foreach (var ch in _clips[ActiveClip].Channels)
                        {
                            var jp = locals[ch.JointIndex];
                            if (ch.Property == "translation") jp.LocalT = SampleVec3(ch, Time);
                            else if (ch.Property == "rotation") jp.LocalR = SampleQuat(ch, Time);
                            else if (ch.Property == "scale") jp.LocalS = SampleVec3(ch, Time);
                            locals[ch.JointIndex] = jp;
                        }
                    }
                    var worlds = new Matrix4x4[_joints.Count];
                    var done = new bool[_joints.Count];
                    Matrix4x4 Resolve(int i)
                    {
                        if (done[i]) return worlds[i];
                        var (t, r, s) = locals[i];
                        var lm = Matrix4x4.CreateScale(s) * Matrix4x4.CreateFromQuaternion(r) * Matrix4x4.CreateTranslation(t);
                        worlds[i] = _joints[i].Parent < 0 ? lm : lm * Resolve(_joints[i].Parent);
                        done[i] = true;
                        return worlds[i];
                    }
                    for (int i = 0; i < _joints.Count; i++) Resolve(i);
                    return worlds;
                }

                private Matrix4x4[] ComputeSkinMatrices(Matrix4x4[] worlds)
                {
                    var skin = new Matrix4x4[worlds.Length];
                    for (int i = 0; i < worlds.Length; i++) skin[i] = _joints[i].InverseBind * worlds[i];
                    return skin;
                }

                private static VertexPositionNormalTexture[] SkinVertices(Primitive p, Matrix4x4[] skin)
                {
                    var output = new VertexPositionNormalTexture[p.BindVertices.Length];
                    for (int i = 0; i < p.BindVertices.Length; i++)
                    {
                        var infl = p.Influences[i];
                        var w = p.Weights[i];
                        var total = w.X + w.Y + w.Z + w.W;
                        if (total <= 0.0001f) { output[i] = p.BindVertices[i]; continue; }
                        Matrix4x4 acc = default;
                        Acc(ref acc, skin, (int)infl.X, w.X);
                        Acc(ref acc, skin, (int)infl.Y, w.Y);
                        Acc(ref acc, skin, (int)infl.Z, w.Z);
                        Acc(ref acc, skin, (int)infl.W, w.W);
                        var bv = p.BindVertices[i];
                        var v3 = Vector3.Transform(new Vector3(bv.Position.X, bv.Position.Y, bv.Position.Z), acc);
                        var n3 = Vector3.Normalize(Vector3.TransformNormal(new Vector3(bv.Normal.X, bv.Normal.Y, bv.Normal.Z), acc));
                        output[i] = new VertexPositionNormalTexture(new XnaVector3(v3.X, v3.Y, v3.Z), new XnaVector3(n3.X, n3.Y, n3.Z), bv.TextureCoordinate);
                    }
                    return output;
                }

                private static void Acc(ref Matrix4x4 acc, Matrix4x4[] joints, int idx, float w)
                {
                    if (w <= 0 || idx < 0 || idx >= joints.Length) return;
                    var m = joints[idx];
                    acc.M11 += m.M11 * w; acc.M12 += m.M12 * w; acc.M13 += m.M13 * w; acc.M14 += m.M14 * w;
                    acc.M21 += m.M21 * w; acc.M22 += m.M22 * w; acc.M23 += m.M23 * w; acc.M24 += m.M24 * w;
                    acc.M31 += m.M31 * w; acc.M32 += m.M32 * w; acc.M33 += m.M33 * w; acc.M34 += m.M34 * w;
                    acc.M41 += m.M41 * w; acc.M42 += m.M42 * w; acc.M43 += m.M43 * w; acc.M44 += m.M44 * w;
                }

                private static Vector3 SampleVec3(Channel ch, float t)
                {
                    if (ch.Vec3.Length == 0) return Vector3.Zero;
                    if (ch.Vec3.Length == 1) return ch.Vec3[0];
                    var times = ch.Times;
                    if (t <= times[0]) return ch.Vec3[0];
                    if (t >= times[^1]) return ch.Vec3[^1];
                    for (int i = 0; i < times.Length - 1; i++)
                        if (t <= times[i + 1])
                            return Vector3.Lerp(ch.Vec3[i], ch.Vec3[i + 1], (t - times[i]) / (times[i + 1] - times[i]));
                    return ch.Vec3[^1];
                }

                private static Quaternion SampleQuat(Channel ch, float t)
                {
                    if (ch.Quat.Length == 0) return Quaternion.Identity;
                    if (ch.Quat.Length == 1) return ch.Quat[0];
                    var times = ch.Times;
                    if (t <= times[0]) return ch.Quat[0];
                    if (t >= times[^1]) return ch.Quat[^1];
                    for (int i = 0; i < times.Length - 1; i++)
                        if (t <= times[i + 1])
                            return Quaternion.Normalize(Quaternion.Slerp(ch.Quat[i], ch.Quat[i + 1], (t - times[i]) / (times[i + 1] - times[i])));
                    return ch.Quat[^1];
                }

                // --- Data types --------------------------------------------------------------

                private sealed class Joint
                {
                    public string Name = "";
                    public Vector3 LocalT;
                    public Quaternion LocalR = Quaternion.Identity;
                    public Vector3 LocalS = Vector3.One;
                    public Matrix4x4 InverseBind = Matrix4x4.Identity;
                    public int Parent = -1;
                }

                private sealed class Primitive
                {
                    public bool IsSkinned;
                    public VertexPositionNormalTexture[] BindVertices = Array.Empty<VertexPositionNormalTexture>();
                    public int[] Indices = Array.Empty<int>();
                    public Vector4[] Influences = Array.Empty<Vector4>();
                    public Vector4[] Weights = Array.Empty<Vector4>();
                }

                private sealed class Channel
                {
                    public int JointIndex;
                    public string Property = "translation";
                    public float[] Times = Array.Empty<float>();
                    public Vector3[] Vec3 = Array.Empty<Vector3>();
                    public Quaternion[] Quat = Array.Empty<Quaternion>();
                }

                private sealed class Clip
                {
                    public string Name = "";
                    public float Duration;
                    public List<Channel> Channels = new();
                }
            }
            """;
    }
}
